#!/usr/bin/env ruby

message = File.read(ARGV[0])

prefixes = [
  [%r{^other/clrs/(\d+)/(\d+)/(\d+)\.},    -> { "clrs; exercise #{$1.to_i}.#{$2.to_i}.#{$3.to_i} – " }],
  [%r{^other/clrs/(\d+)/problems/(\d+)\.}, -> {
    chapter, number = $1, $2
    title = File.read("other/clrs/#$1/problems/#$2.markdown")[/\A#+\s+(.*)/, 1].downcase rescue "FAILED TO GET TITLE"
    "clrs; problem #{chapter.to_i}.#{number.to_i} – #{title}"
  }],
]

files = `git diff-index --cached --name-only HEAD`.split("\n")

exit 0 if files.empty?

first = files.first

prefixes.each do |regexp, title|
  next unless regexp =~ first
  prefix = $&
  header = title.()

  break unless files.all? { |file| file.start_with? prefix }

  File.write ARGV[0], header + message
end
