#!/usr/bin/env ruby

message = File.read(ARGV[0])

prefixes = [
  [%r{^other/clrs/(\d+)/(\d+)/(\d+)\.},    -> { "clrs; exercise #{$1.to_i}.#{$2.to_i}.#{$3.to_i} – " }],
  [%r{^other/clrs/(\d+)/problems/(\d+)\.}, -> { "clrs; problem #{$1.to_i}.#{$2.to_i} – " }],
]

files = `git diff-index --cached --name-only HEAD`.split("\n")

exit 0 if files.empty?

first = files.first

prefixes.each do |regexp, title|
  next unless regexp =~ first
  prefix = $&
  header = title.()

  break unless files.all? { |file| file.start_with? prefix }

  File.write ARGV[0], header + message
end
