; SICP exercise 1.15
;
; The sine of an angle (specified in radians) can be computed by making use of
; the approximation sin(x) ≈ x if x is sufficiently small, and the
; trigonometric identity
;
; sin(r) = 3sin(r/3) - 4sin³(r/3)
;
; to reduce the size of the argument of sin. (For purposes of this exercise an
; angle is considered "sufficiently small" if its magnitude is not greater than
; 0.1 radians.) These ideas are incorporated in the following procedures:
;
; (define (cube x) (* x x x))
; (define (p x) (- (* 3 x) (* 4 (cube x))))
; (define (sine angle)
;   (if (not (> (abs angle) 0.1))
;       angle
;       (p (sine (/ angle 3.0)))))
;
; a. How many times is the procedure p applied when (sine 12.15) is evaluted?
;
; b. What is the order of growth in space and number of steps (as a function
;    of a) used by the process generated by the sine procedure when (sine a)
;    is evaluated?

; This is how the function expands.
;
; (sine 12.15)
; (p (sine 4.05))
; (p (p (sine 1.35)))
; (p (p (p (sine 0.45))))
; (p (p (p (p (sine 0.15)))))
; (p (p (p (p (p (sine 0.05))))))
; (p (p (p (p (p 0.05)))))
; (p (p (p (p 0.1495))))
; (p (p (p 0.4351345505)))
; (p (p 0.975846533167877))
; (p -0.789563114470823)
; -0.39980345741334
;
; As for the questions:
;
; a. p is applied 5 times for (sine 12.15), which also happens to be n / 3,
;    rounded up.
;
; b. The space of (sine n) is n / 3. Its order of growth is Θ(n). The number of
;   steps is (n / 3)C, where C is the number of steps it takes to calculate p
;   once. The number of steps (time taken) has order of growth Θ(logn).
